name: sample-dynamo-plugin
description: Cria um exemplo completo de comunicação com o DynamoDB.
display-name: sample-dynamo-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - net5.0
  - net6.0
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
  - "DynamoDB"
types:
  - app

hooks:
  #dependencyinjection
  - type: edit
    trigger: before-render
    path: "{{computed_inputs.base_path}}/src/{{project_name}}.Infrastructure/DependencyInjection.cs"
    changes:
      - search:
          string: "return services;"
          insert-before:
            value: "services.AddScoped<ICustomerRepository, CustomerRepository>();"
          when:
            not-exists: "services.AddScoped<ICustomerRepository, CustomerRepository>();"
   
      - search:
          string: "using"
          insert-before:
            value: "using {{project_name}}.Domain.Interfaces.Repositories; \n
using {{project_name}}.Infrastructure.Repositories;"
          when:
            not-exists: "using {{project_name}}.Infrastructure.Repositories;"
